name: 'Pull submodule''s update'

on:
  workflow_dispatch:
    inputs:
      submodule_dir:
        description: Fill in the submodule directory that you want to be updated
        type: string
        required: true

jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3

      - name: Checkout submodule repository
        run: |
          pushd ${{ inputs.submodule_dir }}
          git pull
          popd

      - name: Build
        run: |
          echo 'Build'

      - name: Push updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@example.com
          git add ${{ inputs.submodule_dir }}
          git commit -m "Update submodule: ${{ inputs.submodule_dir }}"
          git push

  create_release_draft:
    name: Create release draft
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Todo'

  create_pull_request:
    name: Create pull request
    needs:
      - create_release_draft
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Todo'
