name: 'Pull submodule''s updates'

on:
  workflow_dispatch:
    inputs:
      submodule_dir:
        description: Fill in the submodule directory that you want to be updated
        type: string
        required: true

jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      VERSION_TAG: ${{ steps.calculate_version.outputs.version_tag }}
      HEAD_BRANCH: ${{ steps.push.outputs.HEAD_BRANCH }}
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout submodule repository
        run: |
          pushd ${{ inputs.submodule_dir }}
          git switch main
          git log origin/main --oneline
          git pull --rebase
          popd

      - name: Build
        run: |
          echo 'Build'

      - name: Calculate semantic version
        id: calculate_version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: v
      - run: |
          echo ${VERSION} | jq
        env:
          VERSION: ${{ toJSON(steps.calculate_version.outputs) }}

      - name: Push updates
        id: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@example.com
          git switch -c ${HEAD_BRANCH}
          git add ${{ inputs.submodule_dir }}
          git commit -m "Update submodule: ${{ inputs.submodule_dir }}"
          git push -u origin ${HEAD_BRANCH}
          git tag ${VERSION_TAG}
          git push origin ${VERSION_TAG}
          echo "HEAD_BRANCH=${HEAD_BRANCH}" > ${GITHUB_OUTPUT}
        env:
          VERSION_TAG: ${{ steps.calculate_version.outputs.version_tag }}
          HEAD_BRANCH: update-submodule-${{ steps.calculate_version.outputs.version_tag }}
#        continue-on-error: true # for debug

  create_release_draft:
    name: Create release draft
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh release create ${VERSION_TAG} --draft --title ${VERSION_TAG}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_TAG: ${{ needs.build.outputs.VERSION_TAG }}

  create_pull_request:
    name: Create pull request
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: echo 'Todo'
      - uses: actions/checkout@v3
      - run: |
          gh pr create --base ${HEAD_BRANCH} --title ${VERSION_TAG} --body "Update submodule\n- candidated version: ${VERSION_TAG}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_TAG: ${{ needs.build.outputs.VERSION_TAG }}
          HEAD_BRANCH: ${{ needs.build.outputs.HEAD_BRANCH }}
