name: 'Pull submodule''s updates'

on:
  workflow_dispatch:
    inputs:
      submodule_dir:
        description: Fill in the submodule directory that you want to be updated
        type: string
        required: true

jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      HEAD_BRANCH: ${{ steps.push.outputs.HEAD_BRANCH }}
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout submodule repository
        run: |
          pushd ${{ inputs.submodule_dir }}
          git switch main
          git log origin/main --oneline
          git pull --rebase
          popd

      - name: Build
        run: |
          echo 'Build'

      - name: Push updates
        id: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@example.com
          git switch -c ${HEAD_BRANCH}
          git add ${{ inputs.submodule_dir }}
          git commit -m "Update submodule: ${{ inputs.submodule_dir }}"
          git push -u origin ${HEAD_BRANCH}
          echo "HEAD_BRANCH=${HEAD_BRANCH}" > ${GITHUB_OUTPUT}
        env:
          HEAD_BRANCH: update-submodule

  create_pull_request:
    name: Create pull request
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: echo 'Todo'
      - uses: actions/checkout@v3
      - run: |
          gh pr create \
            --head ${HEAD_BRANCH} \
            --label ${LABEL} \
            --title 'Update submodule' \
            --body <<EOS \
          Update submodule\
          - target directory: ${{ inputs.submodule_dir }}\
          EOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ needs.build.outputs.HEAD_BRANCH }}
          LABEL: update-submodule
