name: 'Pull submodule''s updates'

on:
  workflow_dispatch:
    inputs:
      submodule_dir:
        description: Fill in the submodule directory that you want to be updated
        type: string
        required: true

jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout submodule repository
        run: |
          pushd ${{ inputs.submodule_dir }}
          git switch main
          git log origin/main --oneline
          git pull --rebase
          popd

      - name: Build
        run: |
          echo 'Build'

      - name: Push updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@example.com
          git add ${{ inputs.submodule_dir }}
          git commit -m "Update submodule: ${{ inputs.submodule_dir }}"
          git push
        continue-on-error: true # for debug

  create_release_draft:
    name: Create release draft
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo 'Todo'
      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v0.9.7
#        with:
#          versionSpec: 5.x
#      - name: Calculate semantic version
#        id: gitversion
#        uses: gittools/actions/gitversion/execute@v0.9.7
#      - run: |
#          echo ${GITVERSION} | jq
#        env:
#          GITVERSION: ${{ toJSON(steps.gitversion.outputs) }}
      - name: Calculate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: v
      - run: |
          echo ${VERSION} | jq
        env:
          VERSION: ${{ toJSON(steps.version.outputs) }}
      - run: |
          gh release create v0.0.1 --draft --title v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_pull_request:
    name: Create pull request
    needs:
      - create_release_draft
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Todo'
